geoserver:
  auth: basic # options are basic or token, basic will use beoserver creds, token uses a token auth method
  url: <%= ENV['GEOSERVER_URL'] || "http://localhost:8080/geoserver/rest" %>
  user: <%= ENV['GEOSERVER_USER'] || "admin" %>
  password: <%= ENV['GEOSERVER_PASSWORD'] || "geoserver" %>
  token: <%= ENV['GEO_TOKEN'] %>
