geoserver:
  auth:  # options are basic, token, or bearer, basic will use geoserver creds, token uses a token auth method, bearer uses oauth2 bearer
  url: <%= ENV['GEOSERVER_URL'] || "http://localhost:8080/geoserver/rest" %>
  user: <%= ENV['GEOSERVER_USER'] || "admin" %>
  password: <%= ENV['GEOSERVER_PASSWORD'] || "geoserver" %>
  jwt_secret:  <%= ENV['GEOSERVER_KEY'] %>
  jwt_encode:  <%= ENV['GEOSERVER_ENCODE'] %>
  jwt_user:  <%= ENV['GEOSERVER_USER'] %>